//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_QuoteNumberGenerator
    {
        public int quoteid { get; set; }
        public Nullable<int> basequoteid { get; set; }
        public string year { get; set; }
        public string Maintenance { get; set; }
        public string cdc_salescode { get; set; }
        public Nullable<int> counter { get; set; }
        public Nullable<long> rank { get; set; }
        public string r { get; set; }
        public Nullable<bool> HasChildren { get; set; }
    }
}
