//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_QuoteGroup
    {
        public int CDC_QuoteGroupID { get; set; }
        public int QuoteGroupID { get; set; }
        public int CDC_DefaultItemTypeID { get; set; }
    
        public virtual CDC_DefaultItemType CDC_DefaultItemType { get; set; }
        public virtual QuoteGroup QuoteGroup { get; set; }
    }
}
