//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CDC_Product()
        {
            this.CDC_QuoteItem = new HashSet<CDC_QuoteItem>();
        }
    
        public int CDC_ProductID { get; set; }
        public string VendorName { get; set; }
        public string VendorSKU { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<bool> TaxableCode { get; set; }
        public Nullable<double> LaborPerUnit { get; set; }
        public bool IsDefaultProduct { get; set; }
        public int CDC_DepartmentID { get; set; }
        public Nullable<bool> IsGuaranteed { get; set; }
        public string ProductType { get; set; }
        public string ClientDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> DefaultItemTypeID { get; set; }
    
        public virtual CDC_DefaultItemType CDC_DefaultItemType { get; set; }
        public virtual CDC_Department CDC_Department { get; set; }
        public virtual CDC_ProductType CDC_ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDC_QuoteItem> CDC_QuoteItem { get; set; }
    }
}
