//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_DefaultItemType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CDC_DefaultItemType()
        {
            this.CDC_Product = new HashSet<CDC_Product>();
            this.CDC_QuoteGroup = new HashSet<CDC_QuoteGroup>();
        }
    
        public int CDC_DefaultItemTypeID { get; set; }
        public string CDC_DefaultItemTypeName { get; set; }
        public bool IsSnow { get; set; }
        public int SortOrder { get; set; }
        public string BundleNameText { get; set; }
        public bool IsOptional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDC_Product> CDC_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDC_QuoteGroup> CDC_QuoteGroup { get; set; }
    }
}
