//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_QuoteItem
    {
        public int QuoteItemId { get; set; }
        public int QuoteGroupID { get; set; }
        public int QuoteID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string VendorName { get; set; }
        public string VendorSKU { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Labor { get; set; }
        public Nullable<double> PriceModifier { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<bool> TaxableCode { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public double Quantity { get; set; }
        public string BundleItem { get; set; }
        public Nullable<bool> HideLine { get; set; }
        public Nullable<bool> HidePrice { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public bool ClientOptional { get; set; }
        public Nullable<double> LaborPerUnit { get; set; }
        public Nullable<bool> IsGuaranteed { get; set; }
        public string ProductType { get; set; }
        public string ClientDescription { get; set; }
        public int CDC_DepartmentID { get; set; }
        public Nullable<bool> HideQuantity { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Maintenance_ClientOptedIn { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<bool> IsCommentLineProduct { get; set; }
    
        public virtual CDC_Department CDC_Department { get; set; }
        public virtual CDC_Product CDC_Product { get; set; }
        public virtual CDC_ProductType CDC_ProductType { get; set; }
        public virtual CDC_Quote CDC_Quote { get; set; }
    }
}
