//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_Rate
    {
        public int CDC_RateID { get; set; }
        public Nullable<int> CDC_RateTypeID { get; set; }
        public Nullable<int> CDC_RateCategoryID { get; set; }
        public Nullable<double> CDC_RateValue { get; set; }
    
        public virtual CDC_RateCategory CDC_RateCategory { get; set; }
        public virtual CDC_RateType CDC_RateType { get; set; }
    }
}
