//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_Workorder_SentTo
    {
        public int CDC_Workorder_SentTo_Id { get; set; }
        public Nullable<int> SentBy_UserID { get; set; }
        public Nullable<int> SentTo_UserID { get; set; }
        public Nullable<System.DateTime> Sent_DateTime { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public Nullable<System.DateTime> ModifiedData { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
