//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_WorkOrder_Type
    {
        public int CDC_WorkOrder_Type_ID { get; set; }
        public string CDC_WorkOrder_Type_Name { get; set; }
        public string CDC_WorkOrder_Type_Description { get; set; }
        public string CDC_WorkOrder_Type_Abbreviation { get; set; }
    }
}
