//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDC_WorkOrder_Log
    {
        public int CDC_WorkOrder_Log_Id { get; set; }
        public Nullable<int> CDC_WorkOrder_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
