//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Address
    {
        public int CRMAddressID { get; set; }
        public int CRMCompanyID { get; set; }
        public string ContactName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string PhoneExtension { get; set; }
        public string Email { get; set; }
        public string SiteName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> PhoneTypeID { get; set; }
        public string Phone2 { get; set; }
        public string Phone2Extension { get; set; }
        public Nullable<int> Phone2TypeID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ContactComments { get; set; }
    
        public virtual CRM_Company CRM_Company { get; set; }
        public virtual CRM_PhoneType CRM_PhoneType { get; set; }
        public virtual CRM_PhoneType CRM_PhoneType1 { get; set; }
        public virtual User User { get; set; }
    }
}
