//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRM_Company()
        {
            this.CRM_Address = new HashSet<CRM_Address>();
        }
    
        public int CRMCompanyID { get; set; }
        public int LicenseeID { get; set; }
        public string CompanyName { get; set; }
        public bool Taxable { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> OwnerUserID { get; set; }
        public string TaxIDNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_Address> CRM_Address { get; set; }
        public virtual Licensee Licensee { get; set; }
        public virtual User User { get; set; }
    }
}
