//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteGroupView
    {
        public int QuoteGroupID { get; set; }
        public int QuoteID { get; set; }
        public string BundleName { get; set; }
        public string BundleDescription { get; set; }
        public Nullable<int> BundleQuantity { get; set; }
        public Nullable<int> BundleID { get; set; }
        public Nullable<int> QuoteGroupType { get; set; }
        public Nullable<double> BundlePrice { get; set; }
        public Nullable<int> LineNumber { get; set; }
    }
}
