//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuoteGroup()
        {
            this.CDC_QuoteGroup = new HashSet<CDC_QuoteGroup>();
        }
    
        public int QuoteGroupID { get; set; }
        public int QuoteID { get; set; }
        public string BundleName { get; set; }
        public string BundleDescription { get; set; }
        public Nullable<int> BundleQuantity { get; set; }
        public Nullable<int> BundleID { get; set; }
        public Nullable<int> QuoteGroupType { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<bool> ClientOptedIn { get; set; }
        public Nullable<bool> ShowBox { get; set; }
        public Nullable<bool> Optional { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public Nullable<double> AddedMoneyBundle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDC_QuoteGroup> CDC_QuoteGroup { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
