//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteTermCondition
    {
        public int QuoteID { get; set; }
        public int TermConditionID { get; set; }
        public string OverrideDescription { get; set; }
    }
}
