//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteItemGroupTypeView
    {
        public int QuoteGroupID { get; set; }
        public int QuoteID { get; set; }
        public string BundleName { get; set; }
        public string BundleDescription { get; set; }
        public Nullable<int> BundleQuantity { get; set; }
        public Nullable<int> BundleID { get; set; }
        public Nullable<int> QuoteGroupType { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string Description { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public bool ClientOptional { get; set; }
        public Nullable<bool> HideLine { get; set; }
        public int QuoteItemId { get; set; }
        public Nullable<bool> ShowBox { get; set; }
        public Nullable<bool> HideQuantity { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Optional { get; set; }
    }
}
