//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CRM_Company
    {
        public string LicenseeShortName { get; set; }
        public int CRMCompanyID { get; set; }
        public int LicenseeID { get; set; }
        public string CompanyName { get; set; }
        public bool Taxable { get; set; }
        public string TaxIDNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> OwnerUserID { get; set; }
    }
}
