//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteFastMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_User
    {
        public string LicenseeShortName { get; set; }
        public int UserID { get; set; }
        public int LicenseeID { get; set; }
        public System.Guid aspnet_UserId { get; set; }
        public string LoweredUserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string CDC_SalesCode { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Branch { get; set; }
        public string Position { get; set; }
        public string signatureImageLocation { get; set; }
    }
}
